transports:
  options:
    kafka:
      dsn: '%env(KAFKA_DSN)%'
      broker.list: '%env(KAFKA_BROKER_LIST)%'
      group.id: '%env(KAFKA_GROUP_ID)%'

    rabbitmq:
      host: '%env(RABBITMQ_HOST)%'
      port: '%env(RABBITMQ_PORT)%'
      vhost: '%env(RABBITMQ_VHOST)%'

    redis_stream:
      address: '%env(REDIS_STREAM_ADDRESS)%'
      db: '%env(REDIS_STREAM_DB)%'

  topics:
    alias-topic:
      type: kafka
      consumer_topics:
        - test1
        - test2

    alias-topic2:
      type: kafka
      consumer_topics:
        - test3
        - test4

    alias-topic3:
      type: kafka
      consumer_topics:
        - test5
        - test6